fix(how-to): Examples for adding apks in distroless fail post-install (#3409)
The examples we give for adding apks in distroless environments fails
due to the apk's post-install script `ldconfig-commit.sh` as a result of
not having a shell in the environment to run the script. As a
workaround, we run `apk add` with the `--no-scripts` flag and then run
`ldconfig -r /base-chroot` to regenerate the cache.

## Type of change
<!-- Please be sure to add the appropriate label to your PR. -->
Fixing example code
### What should this PR do?
<!-- Does this PR resolve an issue? Please include a reference to it.
-->
Fixes errors surfaced during customer testing
ref: https://chainguardhelp.zendesk.com/agent/tickets/9823

### Why are we making this change?
<!-- What larger problem does this PR address? -->
The examples are currently incorrect and will fail when following the
instructions

```
 => ERROR [build 6/6] RUN apk add --root /base-chroot so:libcurl.so.4                                                                                                                                           1.3s
------
 > [build 6/6] RUN apk add --root /base-chroot so:libcurl.so.4:
0.069 fetch https://apk.cgr.dev/chainguard/aarch64/APKINDEX.tar.gz
1.159 ERROR: ldconfig-commit.sh: script exited with error 127
------
Dockerfile.dynamic:29
--------------------
  27 |
  28 |     # Customize base image chroot
  29 | >>> RUN apk add --root /base-chroot so:libcurl.so.4
  30 |
  31 |     # Create customized production image from scratch
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c apk add --root /base-chroot so:libcurl.so.4" did not complete successfully: exit code: 99
```

### What are the acceptance criteria? 
<!-- What should be happening for this PR to be accepted? Please list
criteria. -->
<!-- Do any stakeholders need to be tagged in this review? If so, please
add them. -->

### How should this PR be tested?

Any documentation published to Chainguard Academy is reviewed carefully
for accuracy. GUI procedures, API commands, and CLI code snippets in a
draft are run and tested thoroughly — by both the author and the
reviewer — to confirm they work exactly as written. This helps ensure
that readers can follow along and get the same results. See the [`edu`
repo's README](https://github.com/chainguard-dev/edu#testing).

<!-- What should your reviewer do to test this PR? Please list any steps
that are additional to or different from the standard. If you outline
steps in the console, include the console release version in this PR
message. -->

Run through the build steps for both Appendix A and B to ensure they
build correctly and that the updated wording makes sense.