chainctl: fix cosign verify command
I think the versioning output may have changed over time, so this was
returning `v0.1.2` rather than `0.1.2`, throwing off the URLs resulting
in the error:

Error: error during PEM decoding
main.go:74: error during command execution: error during PEM decoding

This fixes the version so the cert can be fetched.