Fixing timestamps (#2125)
[X] Check if this is a typo or other quick fix and ignore the rest :)

There are some invalid timestamps that need to be fixed otherwise the
hugo build fails:

```
❯ hugo serve
Watching for changes in /home/erika/Projects/edu/{archetypes,assets,babel.config.js,content,data,layouts,node_modules,package.json,static}
Watching for config changes in /home/erika/Projects/edu/config/_default, /home/erika/Projects/edu/config/_default/menus
Start building sites … 
hugo v0.123.7+extended linux/amd64 BuildDate=2024-11-06T01:07:23Z VendorInfo=ubuntu:0.123.7-1ubuntu0.2

ERROR render of "page" failed: "/home/erika/Projects/edu/layouts/article/single.html:94:71": execute of template failed: template: article/single.html:94:71: executing "main" at <time.Format>: error calling Format: unable to parse date: 2025-03-0620T08:49:15+00:00
Built in 5339 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/home/erika/Projects/edu/layouts/article/single.html:94:71": execute of template failed: template: article/single.html:94:71: executing "main" at <time.Format>: error calling Format: unable to parse date: 2025-03-0620T08:49:15+00:00

```

Our maintenance tool flagged these:

```
Building content catalog...
Catalog built with 314 items.

Found 7 articles with invalid timestamps.

Found 62 articles not updated in the last 7 months.

Title,Last Updated
/chainguard/chainctl-usage/chainctl-events,N/A
/chainguard/chainctl-usage/chainctl-iam,N/A
/chainguard/chainctl-usage/chainctl-images,N/A
/chainguard/chainctl-usage/chainctl-packages,N/A
/chainguard/chainctl-usage/chainctl-update,N/A
/chainguard/chainctl-usage/chainctl-version,N/A
/chainguard/chainctl-usage/getting-started-with-chainctl,N/A

```

This PR fixes the timestamps in these articles.