chainctl: fix cosign verify command (#2138)
I think the versioning output may have changed over time, so this was
returning `v0.1.2` rather than `0.1.2`, throwing off the URLs resulting
in the error:

Error: error during PEM decoding
main.go:74: error during command execution: error during PEM decoding

This fixes the version so the cert can be fetched.

[x] Check if this is a typo or other quick fix and ignore the rest :)

## Type of change
<!-- Please be sure to add the appropriate label to your PR. -->

### What should this PR do?
<!-- Does this PR resolve an issue? Please include a reference to it.
-->

### Why are we making this change?
<!-- What larger problem does this PR address? -->

### What are the acceptance criteria? 
<!-- What should be happening for this PR to be accepted? Please list
criteria. -->
<!-- Do any stakeholders need to be tagged in this review? If so, please
add them. -->

### How should this PR be tested?
<!-- What should your reviewer do to test this PR? Please list steps.
-->